services:
  ip-echo:
    image: ghcr.io/buildplan/ip-service:latest
    container_name: ip-echo
    restart: unless-stopped
    user: "node"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    ports:
      - "127.0.0.1:4040:4040"
    environment:
      - NODE_ENV=production
      - PORT=4040
    volumes:
      - ./ip_dbs:/app/db:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M

  npm:
    image: 'jc21/nginx-proxy-manager:2.13.5'
    container_name: npm
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
