steps:
  build-and-push:
    image: quay.io/woodpeckerci/plugin-docker
    settings:
      registry: docker.io
      repo: iamdockin/ip-service
      tags: latest
      username: iamdockin
      password:
        from_secret: DOCKER_TOKEN
    when:
      branch: main
      event: push
