steps:
  build-and-push:
    image: quay.io/woodpeckerci/plugin-docker
    settings:
      registry: codeberg.org
      repo: buildplan/ip-service
      tags: latest
      username: buildplan
      password:
        from_secret: CONTAINER_TOKEN
    when:
      branch: main
      event: push
